CREATE TABLE [dbo].[T_User](
	[PK_User] [UNIQUEIDENTIFIER] CONSTRAINT DF_T_User_PK_User DEFAULT NEWID() NOT NULL,
	[DisplayName] [NVARCHAR](60) NOT NULL,
	[UserName] [VARCHAR](30) NOT NULL,
	[Email] [VARCHAR](50) NOT NULL,
	[Password] [VARCHAR](50) NOT NULL,
	[CreatedDateUTC] [DATETIME] CONSTRAINT DF_T_User_CreatedDateUTC DEFAULT GETUTCDATE() NOT NULL,
	CONSTRAINT [T_User_PK_User] PRIMARY KEY CLUSTERED
	(
		[PK_User] ASC
	)
)
GO
